version: '3'

networks:
  test:
    name: fabric_test

services:

  ca:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
      - FABRIC_CA_SERVER_CSR_HOSTS=peer0.bank.yadadev.com,peer0.edb.yadadev.com,peer0.edu1.yadadev.com,peer0.edu2.yadadev.com,localhost
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca
    networks:
      - test
