version: '3'

networks:
  supervision_demo:
    name: supervision_demo

services:
  # 数据库配置
  supervision_demo_mysql:
    container_name: supervision_demo_mysql
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: yadadb
      MYSQL_USER: yadadb
      MYSQL_PASSWORD: yadadb
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - supervision_demo
    volumes:
      - "../serverUSV/docker/init:/docker-entrypoint-initdb.d"
  # 后台服务配置
  supervision_demo_server:
    image: node:latest
    user: "node"
    working_dir: /home/node/app/
    command: /home/node/wait_for.sh supervision_demo_mysql:3306 -- npm run demo
    environment:
      - DB_HOST=supervision_demo_mysql
    volumes:
      - ../serverUSV:/home/node/app/
      - ./wait_for.sh:/home/node/wait_for.sh
    ports:
      - 3003:3003
    container_name: supervision_demo_server
    depends_on:
      - supervision_demo_mysql
    networks:
      - supervision_demo
  # 消费者端
  supervision_demo_consumer:
    image: node:latest
    user: "node"
    working_dir: /home/node/app/
    command: /home/node/wait_for.sh supervision_demo_server:3003 -- npm run demo
    environment:
      - SERVER_PATH=http://localhost:8080/api
    volumes:
      - ../consumerdemo:/home/node/app/
      - ./wait_for.sh:/home/node/wait_for.sh
    ports:
      - 3000:3000
    container_name: supervision_demo_consumer
    # depends_on:
    #   - supervision_demo_server
    networks:
      - supervision_demo
  # 教育机构端
  supervision_demo_edu:
    image: node:latest
    user: "node"
    working_dir: /home/node/app/
    command: /home/node/wait_for.sh supervision_demo_server:3003 -- npm run demo
    volumes:
      - ../eduMag:/home/node/app/
      - ./wait_for.sh:/home/node/wait_for.sh
    ports:
      - 3001:3001
    container_name: supervision_demo_edu
    depends_on:
      - supervision_demo_server
    networks:
      - supervision_demo
  # 监管机构
  supervision_demo_regulator:
    image: node:latest
    user: "node"
    working_dir: /home/node/app/
    command: /home/node/wait_for.sh supervision_demo_server:3003 -- npm run demo
    volumes:
      - ../regulator-mag-ionic:/home/node/app/
      - ./wait_for.sh:/home/node/wait_for.sh
    ports:
      - 3002:3002
    container_name: supervision_demo_regulator
    depends_on:
      - supervision_demo_server
    networks:
      - supervision_demo
  # 网关
  supervision_demo_nginx:
    image: nginx:latest
    container_name: supervision_demo_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
      - 80:80
    networks:
      - supervision_demo
  # java 加解密通信
  supervision_demo_encrypt:
    image: maven:3.8.6-openjdk-18
    container_name: supervision_demo_encrypt
    command: /root/run_java.sh
    volumes:
      - ../encryptByPubk:/root/app/
      - ./run_java.sh:/root/run_java.sh
    ports:
      - 2999:2999
    networks:
      - supervision_demo

    