version: '3'

networks:
  supervision_demo:
    name: supervision_demo

services:
  # 数据库配置
  supervision_demo_mysql:
    container_name: supervision_demo_mysql
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: yadadb
      MYSQL_USER: yadadb
      MYSQL_PASSWORD: yadadb
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - supervision_demo
    volumes:
      - "../serverUSV/docker/init:/docker-entrypoint-initdb.d"
  # 后台服务配置
  supervision_demo_server:
    image: node:latest
    user: "node"
    working_dir: /home/node/app/
    command: /home/node/wait_for.sh -t 0 supervision_demo_mysql:3306 -- npm run demo
    environment:
      - DB_HOST=supervision_demo_mysql
    volumes:
      - ../serverUSV:/home/node/app/
      - ./wait_for.sh:/home/node/wait_for.sh
    ports:
      - 3003:3003
    container_name: supervision_demo_server
    depends_on:
      - supervision_demo_mysql
    networks:
      - supervision_demo
    restart: always
  # 消费者端
  supervision_demo_consumer:
    image: node:latest
    user: "node"
    working_dir: /home/node/app/
    command: /home/node/wait_for.sh -t 0 supervision_demo_server:3003 -- npm run demo
    environment:
      - NEXT_PUBLIC_SERVER_PATH=http://${host}:8080/api/consumer
      - NEXT_PUBLIC_ROOT_PATH=/consumer
    volumes:
      - ../consumerdemo:/home/node/app/
      - ./wait_for.sh:/home/node/wait_for.sh
    ports:
      - 3000:3000
    container_name: supervision_demo_consumer
    depends_on:
      - supervision_demo_server
    networks:
      - supervision_demo
  # 教育机构端
  supervision_demo_edu:
    image: node:latest
    user: "node"
    working_dir: /home/node/app/
    command: /home/node/wait_for.sh -t 0 supervision_demo_consumer:3000 -- npm run demo
    environment:
      - NEXT_PUBLIC_SERVER_PATH=http://${host}:8080/api/edu
      - NEXT_PUBLIC_ROOT_PATH=/edu
      - ENV_RUNTIME=test
    volumes:
      - ../eduMag:/home/node/app/
      - ./wait_for.sh:/home/node/wait_for.sh
    ports:
      - 3001:3001
    container_name: supervision_demo_edu
    depends_on:
      - supervision_demo_server
    networks:
      - supervision_demo
  # 监管机构
  supervision_demo_edb:
    image: node:latest
    user: "node"
    working_dir: /home/node/app/
    command: /home/node/wait_for.sh -t 0 supervision_demo_edu:3001 -- npm run demo
    environment:
      - NEXT_PUBLIC_SERVER_PATH=http://${host}:8080/api/edb
      - NEXT_PUBLIC_ROOT_PATH=/edb
      # - ENV_RUNTIME=test
    volumes:
      - ../regulator-mag-ionic:/home/node/app/
      - ./wait_for.sh:/home/node/wait_for.sh
    ports:
      - 3002:3002
    container_name: supervision_demo_edb
    depends_on:
      - supervision_demo_server
    networks:
      - supervision_demo
  # 网关
  supervision_demo_nginx:
    image: nginx:latest
    container_name: supervision_demo_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html/:/usr/share/nginx/html/
    ports:
      - 8080:8080
      # # - 80:80
    networks:
      - supervision_demo
    depends_on:
      - supervision_demo_server
      - supervision_demo_consumer
      - supervision_demo_edu
      - supervision_demo_edb
    