@startuml pc端消费
消费者 -> 监管消费者服务端 : 购买课程
监管消费者服务端 -> db : 生成订单号并保存
监管消费者服务端 -> 数字人民币: 获取付款二维码
监管消费者服务端 ->  消费者 : 返回订单号和付款二维码
消费者 -> 数字人民币 : 支付
监管消费者服务端 -> 数字人民币 : 轮询查询支付状况
alt 查询到成功支付
监管消费者服务端 -> DB : 修改订单状态，划拨
监管消费者服务端 -> 消费者 : 通知页面跳转
else 到达最大等待时间仍未查询到成功支付
监管消费者服务端 -> DB : 修改订单状态为关闭
end
@enduml