@startuml 退课
消费者 -> 消费者端: 发起退课申请
消费者端 -> DB: 记录退课申请
消费者端 -> 消费者: 教育机构补偿要求
教育机构 -> 教育机构端: 发起退课申请
教育机构端 -> DB: 记录教育机构提出的要求
教育机构 -> 教育机构端口: 教育机构补偿要求
alt 教育机构提出要求与消费者提出要求相同
教育机构 -> 数字人民币 : 进行退款
教育机构端 -> DB: 记录划拨，修改争端表状态
else 
教育机构端 -> DB:修改争端表状态
end
教育机构端 -> 教育机构: 处理完成
@enduml    